repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        language: system
        entry: uv run ruff format
        types: [python]
        pass_filenames: true
      - id: ruff-lint
        name: ruff lint
        language: system
        entry: uv run ruff check --fix
        types: [python]
        pass_filenames: true
      - id: mypy
        name: mypy
        language: system
        entry: uv run mypy
        types: [python]
        pass_filenames: false
        args: [src/]
